[[pages]]
path = "app.py"
name = "IntroduÃ§Ã£o"
icon = "ğŸ›¢ï¸"

[[pages]]
path = "pages/page_2.py"
name = "DataFrame"
icon = "ğŸ“"

[[pages]]
path = "pages/page_3.py"
name = "Projeto"
icon = "ğŸ“‹"

[[pages]]
path = "pages/page_4.py"
name = "AnÃ¡lise"
icon = "ğŸ”"

[[pages]]
path = "pages/page_5.py"
name = "Modelo"
icon = "ğŸ“ˆ"

[[pages]]
path = "pages/page_6.py"
name = "Dashboard"
icon = "ğŸ“Š"

[[pages]]
path = "pages/page_7.py"
name = "ReferÃªncias"
icon = "ğŸ“‘"